name: Algs
main: mc.Setup
version: 0.1

commands:
   startgame:
     description: Starts the game.
     usage: /<command> <floors> <eggs>
   stopgame:
     description: Stops the game.
     usage: /<command>